"""empty message

Revision ID: 309a55b36305
Revises: 6890a0d527a0
Create Date: 2024-04-05 00:40:10.658739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309a55b36305'
down_revision = '6890a0d527a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('cart_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart_items', 'carts', ['cart_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_column('cart_items', 'cart_id')
    # ### end Alembic commands ###
