"""empty message

Revision ID: 49f781251ff5
Revises: 3babce087c5f
Create Date: 2024-04-30 19:17:44.191011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f781251ff5'
down_revision = '3babce087c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('code_file', sa.String(length=200), nullable=True, server_default=''))
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('image_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('products', 'code_file')
    # ### end Alembic commands ###
