"""empty message

Revision ID: 6f17e765e3e3
Revises: da29b548c4f2
Create Date: 2024-04-26 01:30:06.138189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f17e765e3e3'
down_revision = 'da29b548c4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('participations_user_id_fkey', 'participations', type_='foreignkey')
    op.create_foreign_key(None, 'participations', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participations', type_='foreignkey')
    op.create_foreign_key('participations_user_id_fkey', 'participations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('participations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
