"""empty message

Revision ID: 7361a971eda1
Revises: 2693331030c6
Create Date: 2024-05-15 17:16:58.167758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7361a971eda1'
down_revision = '2693331030c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_room_users')
    op.add_column('chat_rooms', sa.Column('user1_id', sa.Integer(), nullable=False))
    op.add_column('chat_rooms', sa.Column('user2_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chat_rooms', 'users', ['user1_id'], ['id'])
    op.create_foreign_key(None, 'chat_rooms', 'users', ['user2_id'], ['id'])
    op.drop_column('chat_rooms', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_rooms', type_='foreignkey')
    op.drop_constraint(None, 'chat_rooms', type_='foreignkey')
    op.drop_column('chat_rooms', 'user2_id')
    op.drop_column('chat_rooms', 'user1_id')
    op.create_table('chat_room_users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chat_room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], name='chat_room_users_chat_room_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chat_room_users_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'chat_room_id', name='chat_room_users_pkey')
    )
    # ### end Alembic commands ###
