"""empty message

Revision ID: 9c7c62da2323
Revises: a34bf39b6ca2
Create Date: 2024-04-17 12:10:43.267970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7c62da2323'
down_revision = 'a34bf39b6ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('type', sa.String(length=20), nullable=False))
    op.drop_constraint('categories_name_key', 'categories', type_='unique')
    op.create_unique_constraint('unique_category', 'categories', ['name', 'type'])
    op.add_column('products', sa.Column('language_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'categories', ['language_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'language_id')
    op.drop_constraint('unique_category', 'categories', type_='unique')
    op.create_unique_constraint('categories_name_key', 'categories', ['name'])
    op.drop_column('categories', 'type')
    # ### end Alembic commands ###
