"""empty message

Revision ID: cb65a5bf187b
Revises: c2832050a16f
Create Date: 2024-05-09 04:34:47.023371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb65a5bf187b'
down_revision = 'c2832050a16f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundings', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundings', 'is_active')
    # ### end Alembic commands ###
